eval_config:
  cache_file: null
  tasks:
    leaderboard_musr:
      num_fewshot: null

    leaderboard_bbh:
      num_fewshot: null

    leaderboard_mmlu_pro:
      num_fewshot: 5

    leaderboard_gpqa:
      num_fewshot: null

    leaderboard_ifeval:
      num_fewshot: null

train_config:
  batch_size: 1
  lr: 0.0001
  max_seq_length: 1024
  max_steps: 1000
  warmup_steps: 100
  weight_decay: 0.01
  epochs: 1

  datasets:
    - name: "nickrosh/Evol-Instruct-Code-80k-v1"
      num_samples: 1000

run_name: "Qwen-1.5B-redistill-7B-45k-samples-eval"
model_name: "Qwen-1.5B-redistill-7B-45k-samples-eval"
run_initial_eval: true
run_training: false


student_model: "siro1/Qwen-1.5B-redistill-7B-45k-samples"
teacher_model: null
