eval_config:
  tasks:
    leaderboard_musr:
      num_fewshot: null

    leaderboard_mmlu_pro:
      num_fewshot: 5

    leaderboard_gpqa:
      num_fewshot: null

    leaderboard_ifeval:
      num_fewshot: null
    leaderboard_bbh:
      num_fewshot: null
    
    leaderboard_musr_murder_mysteries:
      num_fewshot: null
    
    leaderboard_musr_object_placements:
      num_fewshot: null
    
    leaderboard_musr_team_allocation:
      num_fewshot: null



  # batch_size: null
  # max_samples: null
  push_to_hub: true

run_name: "r1-qwen-1.5b-eval"

teacher_model: null
